# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='locationnewsevent',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.News'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(db_column='id_categ', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.Categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotosUrls'),
        ),
        migrations.AddField(
            model_name='news',
            name='photos',
            field=models.ManyToManyField(through='proj.NewsPhotos', to='proj.PhotosUrls'),
        ),
        migrations.AddField(
            model_name='newsphotos',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.News'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsphotos',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotosUrls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinions',
            name='photos',
            field=models.ManyToManyField(through='proj.OpinionsImages', to='proj.PhotosUrls'),
        ),
        migrations.AddField(
            model_name='opinionsimages',
            name='opinion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.Opinions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinionsimages',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotosUrls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinionstotags',
            name='opinions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.Opinions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinionstotags',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.Tags'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoalbumstitle',
            name='photos',
            field=models.ManyToManyField(through='proj.PhotosInAlbums', to='proj.PhotosUrls'),
        ),
        migrations.AddField(
            model_name='photoalbumstitle',
            name='title_image',
            field=models.ForeignKey(blank=True, db_column='title_image', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotosUrls'),
        ),
        migrations.AddField(
            model_name='photosinalbums',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotoAlbumsTitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photosinalbums',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotosUrls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpoint',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.PhotosUrls'),
        ),
        migrations.AddField(
            model_name='tourstopoints',
            name='point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.TourPoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourstopoints',
            name='tours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proj.Tours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_fav',
            field=models.IntegerField(),
        ),
    ]
