# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('coord', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attractions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesLinks',
            fields=[
                ('parent_id', models.IntegerField()),
                ('child_id', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categories_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationNewsEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coord', models.TextField()),
            ],
            options={
                'db_table': 'location_news_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('header', models.CharField(max_length=-1)),
                ('content', models.TextField()),
                ('is_fav', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('scale', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('title', models.TextField()),
                ('headline', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opinions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionsImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opinions_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionsLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opinion_id', models.IntegerField()),
                ('coord', models.TextField()),
            ],
            options={
                'db_table': 'opinions_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionsToTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'opinionstotags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbumsTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photoalbums_title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotosInAlbums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'photos_in_albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotosUrls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'photos_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('coordinates', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tour_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToursToPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tours_to_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('hashpass', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
