# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standartRouteHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categorieslinks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locationnewsevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newsphotos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='opinions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='opinionsimages',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='opinionslocations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='opinionstotags',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='photoalbumstitle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='photosinalbums',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='photosurls',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tourpoint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tourstopoints',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
